### ISSUE TITLE
return total amount

### ISSUE THREAD

**Issue by jon4hz** [deliton/eldenring-api#1]
Hey, super cool API! I just started playing around with it a bit and noticed that the API doesn't return the total amount of possible data, which makes pagination a bit tricky. Could you add a field like `total` next to `count`, so people don't have to "brute force" check if there is more data available than initially requested?

**Comment by deliton** [comment]
Hey Jon4hz. that's a great idea! I'll add it to Wednesday release :)

**Comment by deliton** [comment]
`total` added in 0.1.1 release. Thanks for the suggestion :)
