### ISSUE TITLE
Eccentric's Manchettes description is incorrect

### ISSUE THREAD

**Issue by kartikdc** [deliton/eldenring-api#10]
Should be:

> The knight Jerren's manchettes.
>
> Jerren preferred a nomadic existence, but after spending time as a guest of the Carian royals, he became the guest commander for General Radahn. And for the first time, the restless tumbleweed would be bound by honorable oath.

Currently is:

> Gauntlets of the Cleanrot Knights, celebrated for their undefeated campaign in the Shattering. The Cleanrot Knights vowed to fight alongside Malenia, despite the inevitable, if gradual, putrefaction of their flesh. Their acceptance of their fate made these battles fiercest of all.

**Comment by deliton** [comment]
Good catch! I'll publish the fixed version in a few days. Thanks a lot :)

**Comment by kartikdc** [comment]
@deliton Some descriptions are missing as well:

```
in api/public/data on  main [✘?] via Python v3.8.10 (env)
 ❯ python createdb.py
MISSING DESCRIPTION: Maliketh's Gauntlets
MISSING DESCRIPTION: Mushroom Body
MISSING DESCRIPTION: Gelmir Knight Greaves
MISSING DESCRIPTION: White Reed Gauntlets
MISSING DESCRIPTION: Fur Raiment
MISSING DESCRIPTION: Godrick Soldier Gauntlets
MISSING DESCRIPTION: Bloodhound Knight Greaves
MISSING DESCRIPTION: Tree-and-beast Surcoat
MISSING DESCRIPTION: Leather Gloves
MISSING DESCRIPTION: White Reed Greaves
MISSING DESCRIPTION: Scaled Gauntlets
MISSING DESCRIPTION: Godrick Soldier Greaves
MISSING DESCRIPTION: Cleanrot Armor
MISSING DESCRIPTION: Mushroom Legs
MISSING DESCRIPTION: Leather Boots
MISSING DESCRIPTION: Note: Demi-human Mobs
MISSING DESCRIPTION: Remembrance Of Hoarah Loux
```

**Comment by deliton** [comment]
Thanks! This was fixed in the last release
