### ISSUE TITLE
GraphQL CORS

### ISSUE THREAD

**Issue by willsoto** [deliton/eldenring-api#12]
Hi there. Great API and thanks for all the work putting this together!

I am trying to hit this API from the browser and getting a CORS pre-flight issue. Specifically:

`405 Method Not Allowed`

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://eldenring.fanapis.com/api/graphql. (Reason: CORS preflight response did not succeed). Status code: 405.
```

I do see in the Response Headers that you have `access-control-allow-origin: *` (which is correct if you intend to allow browsers to hit the API). But I also see there is an [`Allow` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Allow) which is restricted to `GET, POST`. I believe this might be the problem. 

Since you are using Next.js, I think we can just follow the example [here](https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-micro/README.md#cors-example) to fix this.

I am happy to make a PR with these changes if you agree with the root cause and the suggestion solution. Please let me know. Thank you.

**Comment by deliton** [comment]
Hey Will. Thanks for reaching out. Feel free to raise a PR, all help is welcome
