### ISSUE TITLE
data.requires[{ inconsistent array}]

### ISSUE THREAD

**Issue by TheRayCannon** [deliton/eldenring-api#16]
This is just looking at the "sorceries" request, but I wouldnt be shocked if it went further. So when looking at the array of "requires" it is too inconsistent to use as a source of sorting the overall fetch.  we see that there are some which contain "intelligence" "faith" and "arcane" (ideal) while others will be missing some of the attributes or will have abbreviated the name  (check out  "Carian Slicer" requires [{"name": "Int", "amount": 14]) this is making it impossible to cater a list based on these nested arrays. Is there anyway to fix this across all fields (including weapons, incantations, ect?)

Thanks so much!

**Comment by deliton** [comment]
Hey RayCannon! Thanks for pointing this out! We'll do a release next week and those things will hopefully get fixed.

**Comment by deliton** [comment]
Hey! I haven't had the time to address all the bugs, but just released a patch that fixes most of those issues. Thanks for the issue ;)
