### ISSUE TITLE
Inconsistency with Weapon Category 

### ISSUE THREAD

**Issue by RyanGreenburg** [deliton/eldenring-api#17]
There are plural and non plural versions of categories, ie: `Greatsword` and `Greatswords` , `Dagger` and `Daggers`.  This makes using the `category` argument tricky due to having to handle both category arguments for one category type.

**Comment by deliton** [comment]
thanks for finding that. Fix coming in the next release.

**Comment by deliton** [comment]
Hey Ryan! Sorry it took so long to fix this. Just released a patch that resolves this naming issue. Thanks for pointing that out.
