### ISSUE TITLE
Rounded Values + nulls where 0s should be

### ISSUE THREAD

**Issue by ItamiKyojin** [deliton/eldenring-api#19]
Looking at some values from armor pieces, I could see all(?) values have been rounded down. E.g.: Black Dumpling
Your values = dmgNegation: 2 3 2 2 3 3 3 3; resistance: 24 15 null 20 null
Actual values = dmgNegation: 2.8, 3.1, 2.8, 2.8, 3.1, 3.4, 3.6, 3.1; resistance: 24 15 0 20 0

It would be awesome, if you could get more accurate numbers and maybe even replace the nulls with 0s.

**Comment by deliton** [comment]
Hey Itami! Just released a patch that fixes some naming issues and replaced the nulls with zeros. I'm working on a script that will re-scrape the data with the updated values. Thanks for the issue :)
