### ISSUE TITLE
Making an iOS app

### ISSUE THREAD

**Issue by Dimillian** [deliton/eldenring-api#2]
Hello, 

Thanks for this great API! I’ve sent you messages over Reddit but I have no ideas if you read those, so I’m making an issue here :) 
I’m making an iOS app using your GQL API, you can see it here: https://github.com/Dimillian/The-Roundtable
Do you plan to add a search API? Would be wonderful. If you’re not planing to do it I can look into it. Also some kind of filter / sort would be great. For example being able to request weapons by scaling rank or armor by weight. 

Thanks for this great API! 

Here is some screens: 
<img width="524" alt="Screenshot 2022-03-21 at 19 20 47" src="https://user-images.githubusercontent.com/535509/159425855-14fadcc7-6918-4c36-8186-cb087cb7b1cf.png">
<img width="524" alt="Screenshot 2022-03-21 at 21 34 25" src="https://user-images.githubusercontent.com/535509/159425865-217099cd-4438-42ab-a3ff-b4aef532f03d.png">
<img width="524" alt="Screenshot 2022-03-21 at 21 34 31" src="https://user-images.githubusercontent.com/535509/159425872-a3e87dd5-532f-4e9d-9f32-aaae4b661503.png">

**Comment by deliton** [comment]
Hey Dimillian. Thanks a lot. A search feature is definetely necessary. I followed you on Reddit so lets sync about our ideas of improvement.

**Comment by deliton** [comment]
Closing this so we can keep talking via Reddit :)
