### ISSUE TITLE
ashesofwar api endpoint could not be found

### ISSUE THREAD

**Issue by Tr4shL0rd** [deliton/eldenring-api#3]
https://eldenring.fanapis.com/api/ashesofwar returns a 404 error when visiting the url

**Comment by deliton** [comment]
Thanks for pointing this out. Fix is gout out later today

**Comment by deliton** [comment]
seemed like a bug related to the lambda function still having the camelcase version. Changed route to `ashes`, added in 0.1.1 release. Thanks for pointing this out  :)
