### ISSUE TITLE
GQL Search not functioning like REST 

### ISSUE THREAD

**Issue by RyanGreenburg** [deliton/eldenring-api#8]
GraphQL query by name will not return results unless name string matches exactly. Searching a partial string in REST returns data.

<img width="500" alt="Screen Shot 2022-03-29 at 7 45 15 PM" src="https://user-images.githubusercontent.com/47044884/160735590-a628e124-b8e1-4d51-8584-e73bae2a64f1.png">

<img width="500" alt="Screen Shot 2022-03-29 at 7 45 25 PM" src="https://user-images.githubusercontent.com/47044884/160735596-ea25278d-7da2-4a8c-8f88-5a6df0f7eb32.png">

<img width="500" alt="Screen Shot 2022-03-29 at 8 00 56 PM" src="https://user-images.githubusercontent.com/47044884/160735653-c50c640b-8a8d-443f-b9b8-ab6cb5dbcf97.png">

**Comment by deliton** [comment]
Oh unlike REST version, GraphQL uses `search` param to do search. It should have been more well documented, sorry :)

![image](https://user-images.githubusercontent.com/47995046/160736190-41fea3f8-651b-4a02-8858-7b43c4f2d3ee.png)

**Comment by RyanGreenburg** [comment]
Ah perfect! Thanks for the quick reply.
